services:
  hmsnutritionist:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmsnutritionist
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmsnutritionist-postgresql:5432/hmsnutritionist
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmsnutritionist-postgresql:5432/hmsnutritionist
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmsnutritionist-postgresql:
    image: postgres:14.5
    volumes:
      - /mnt/disks/vol-db/nutritionist-db:/var/lib/postgresql/data
    ports:
      - '5465:5432'
    environment:
      - POSTGRES_USER=hmsnutritionist
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
