name: Build and Deploy Nutritionist Microservices

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-west1 # TODO: update region of the Artifact Registry
  REPOSITORY: hmsrepository2 # TODO: update to Artifact Registry docker repository
  IMAGE: hmsnutritionist

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Login to google cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
        
    # Login to google Artifact Registry    
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: us-west1-docker.pkg.dev/hmscapstoneproject/hmsregistry2
        username: _json_key
        password: ${{ secrets.GKE_SA_KEY }}
        
    # Build and Deploy the Docker Image
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Build with Gradle and Push the Google Artifact Repository
      run: |
        ./gradlew bootJar -Pprod jib -Djib.to.image="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"
   
        
   # - name: Build with Maven
   #   run: |
   #      mvn compile com.google.cloud.tools:jib-maven-plugin:3.3.1:build \
   #     -Dspring-boot.run.profiles=prod \
   #     -Dimage="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"
                      
